// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace WineRecommendationMVC
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"fixed acidity")]
            public float Fixed_acidity { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"volatile acidity")]
            public float Volatile_acidity { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"citric acid")]
            public float Citric_acid { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"residual sugar")]
            public float Residual_sugar { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"chlorides")]
            public float Chlorides { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"free sulfur dioxide")]
            public float Free_sulfur_dioxide { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"total sulfur dioxide")]
            public float Total_sulfur_dioxide { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"density")]
            public float Density { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"pH")]
            public float PH { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"sulphates")]
            public float Sulphates { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"alcohol")]
            public float Alcohol { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"quality")]
            public float Quality { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"fixed acidity")]
            public float Fixed_acidity { get; set; }

            [ColumnName(@"volatile acidity")]
            public float Volatile_acidity { get; set; }

            [ColumnName(@"citric acid")]
            public float Citric_acid { get; set; }

            [ColumnName(@"residual sugar")]
            public float Residual_sugar { get; set; }

            [ColumnName(@"chlorides")]
            public float Chlorides { get; set; }

            [ColumnName(@"free sulfur dioxide")]
            public float Free_sulfur_dioxide { get; set; }

            [ColumnName(@"total sulfur dioxide")]
            public float Total_sulfur_dioxide { get; set; }

            [ColumnName(@"density")]
            public float Density { get; set; }

            [ColumnName(@"pH")]
            public float PH { get; set; }

            [ColumnName(@"sulphates")]
            public float Sulphates { get; set; }

            [ColumnName(@"alcohol")]
            public float Alcohol { get; set; }

            [ColumnName(@"quality")]
            public uint Quality { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("quality");
            if (labelColumn == null)
            {
                throw new Exception("quality column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<float>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
